# Generated by Django 5.1.3 on 2024-11-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10)),
                ('year_of_manufacture', models.IntegerField()),
                ('last_accident_date', models.DateTimeField()),
                ('compensation_amount', models.IntegerField()),
                ('passengers_injured', models.CharField(max_length=3)),
            ],
        ),
    ]
