# Generated by Django 5.1.3 on 2024-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10)),
                ('year_of_manufacture', models.IntegerField()),
                ('last_accident_date', models.DateTimeField()),
                ('compensation_amount', models.IntegerField()),
                ('passengers_injured', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('passport_series', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
